/* generated by scripts/codegen-ts.mjs; do not edit */

// types.schema.json
export interface PolyporeTypes {
  [k: string]: unknown;
}

// manifest.schema.json
export interface PanelManifest {
  schemaVersion: 1;
  id: string;
  title: string;
  icon: string;
  version: string;
  author?: {
    name: string;
    url?: string;
  };
  description?: string;
  entry: string;
  permissions: (
    | 'state.read'
    | 'editor.read'
    | 'editor.write'
    | 'editor.decorate'
    | 'knowledge.read'
    | 'knowledge.write'
    | 'tasks.read'
    | 'tasks.write'
    | 'diagnostics.read'
    | 'verify.read'
    | 'verify.run'
    | 'iterate.run'
    | 'chat.read'
    | 'chat.send'
    | 'chat.context'
    | 'agent.control'
    | 'history.read'
    | 'history.fork'
    | 'history.revert'
    | 'workspace.read'
    | 'workspace.write'
    | 'preview.read'
    | 'preview.register'
    | 'preview.refresh'
    | 'terminal.spawn'
    | 'terminal.stop'
    | 'terminal.write'
    | 'terminal.read'
    | 'fs.write'
    | 'ui.notify'
    | 'ui.confirm'
    | 'ui.openExternal'
    | 'ui.statusBar'
    | 'ui.input'
    | 'plugins.read'
    | 'plugins.write'
    | 'secrets.list'
    | 'secrets.use'
    | 'mcp.invoke'
    | 'skills.read'
    | 'skills.write'
    | 'skills.delete'
    | 'skills.invoke'
    | 'debug.read'
    | 'debug.control'
    | 'storage.read'
    | 'storage.write'
    | 'git.read'
    | 'git.write'
    | 'bus.publish'
    | 'http.fetch'
    | 'clipboard.read'
    | 'clipboard.write'
  )[];
  capabilities: (
    | 'memory-dir'
    | 'slash-commands'
    | 'tool-servers'
    | 'compaction'
    | 'phase-reporting'
    | 'permission-flow'
    | 'subagent-spawn'
    | 'streaming'
    | 'tool-use'
  )[];
  category: 'editor' | 'agent' | 'verify' | 'knowledge' | 'runtime' | 'other';
  defaultArea?: 'center' | 'left' | 'right' | 'bottom';
  settings?: PanelSettingSchema;
  manual?: PanelManualContent;
}
export interface PanelSettingSchema {
  fields: unknown[];
  [k: string]: unknown;
}
export interface PanelManualContent {
  summary: string;
  tips: string[];
  externalDocsUrl?: string;
}

// events.schema.json
export type AppEvent =
  | {
      type: 'history:event';
      event: HistoryEvent;
    }
  | {
      type: 'workflow:update';
      nodes: WorkflowNode[];
      edges: WorkflowEdge[];
    }
  | {
      type: 'verify:run-recorded';
      run: VerifyRun;
    }
  | {
      type: 'agent:connection-changed';
      connected: boolean;
      agent: string;
    }
  | {
      type: 'agent:tool-call';
      sessionId: string;
      toolCall: ToolCall;
    }
  | {
      type: 'chat:message';
      sessionId: string;
      message: ChatMessage;
    }
  | {
      type: 'tasks:changed';
      tasks: Task[];
    }
  | {
      type: 'editor:opened';
      path: string;
    }
  | {
      type: 'editor:edited';
      path: string;
      edits: TextEdit[];
    }
  | {
      type: 'diagnostics:changed';
      diagnostics: Diagnostic[];
    }
  | {
      type: 'knowledge:changed';
      path: string;
    }
  | {
      type: 'panel:opened';
      instanceId: string;
      panelId: string;
      area?: 'center' | 'left' | 'right' | 'bottom';
    }
  | {
      type: 'panel:closed';
      instanceId: string;
    }
  | {
      type: 'preview:registered';
      target: PreviewTarget;
    }
  | {
      type: 'preview:refresh-requested';
    }
  | {
      type: 'formation:updated';
      formation: Formation;
    }
  | {
      type: 'state:changed';
      key:
        | 'activeAgent'
        | 'agentConnected'
        | 'workspace'
        | 'activePanel'
        | 'agentPanels'
        | 'branch'
        | 'contextUsedPct'
        | 'context'
        | 'permissionMode'
        | 'loopCycle'
        | 'preview'
        | 'formation'
        | 'tasks'
        | 'diagnostics'
        | 'verifyRuns';
      value: unknown;
    }
  | {
      type: 'plugins:changed';
      plugins: PluginRef[];
    };

export interface HistoryEvent {
  id: string;
  ts: number;
  taskId: string;
  source: 'agent' | 'human';
  kind: 'tool-call' | 'file-write' | 'file-edit' | 'message' | 'phase-change' | 'snapshot';
  agentId?: string;
  toolName?: string;
  phase?: string;
  affectedFiles: string[];
  summary: string;
  payload?: {
    [k: string]: unknown;
  };
  snapshotId?: number;
  worktreeId?: string;
  snapshotCommit?: string;
}
export interface WorkflowNode {
  id: string;
  label: string;
  level: 'phase' | 'sub';
  status: 'pending' | 'running' | 'done' | 'failed' | 'paused';
  [k: string]: unknown;
}
export interface WorkflowEdge {
  id: string;
  source: string;
  target: string;
}
export interface VerifyRun {
  id: string;
  label: string;
  command: string;
  cwd?: string;
  required: boolean;
  status: 'ok' | 'fail' | 'pending';
  exitCode: number | null;
  ranAt: number | null;
  output: string;
  durationMs: number | null;
}
export interface ToolCall {
  id: string;
  sessionId: string;
  agentId: string;
  toolName: string;
  summary: string;
  status: 'ok' | 'live' | 'fail';
  ts: number;
  historyEventId?: string;
}
export interface ChatMessage {
  id: string;
  sessionId: string;
  by: 'user' | 'agent' | 'tool';
  ts: number;
  text: string;
  toolCallId?: string;
}
export interface Task {
  id: string;
  label: string;
  done: boolean;
  parentId?: string;
  panelHint?: string;
  createdAt: number;
  createdBy: 'user' | 'agent';
}
export interface TextEdit {
  range: Range;
  newText: string;
}
export interface Range {
  start: Position;
  end: Position;
}
export interface Position {
  line: number;
  column: number;
}
export interface Diagnostic {
  id: string;
  severity: 'error' | 'warn' | 'info' | 'hint';
  source: string;
  file: string;
  range: Range;
  message: string;
  code?: string | number;
}
export interface PreviewTarget {
  id: string;
  kind: 'site' | 'desktop' | 'mobile' | 'cli' | 'game' | 'test';
  label: string;
  command: string;
  cwd?: string;
  target: string;
  registeredAt: number;
  agentId?: string;
}
export interface Formation {
  schemaVersion: 1;
  taskId: string;
  nodes: FormationNode[];
  edges: WorkflowEdge[];
}
export interface FormationNode {
  id: string;
  role: string;
  detail: string;
  root: boolean;
  status: 'idle' | 'running' | 'waiting' | 'done' | 'failed';
  [k: string]: unknown;
}
export interface PluginRef {
  id: string;
  version: string;
  scope: 'project' | 'user' | 'builtin';
  enabled: boolean;
  installedAt: number;
  [k: string]: unknown;
}

// rpc/envelope.schema.json
export type RpcEnvelope = RpcRequest | RpcSuccessResponse | RpcErrorResponse | RpcEvent;

export interface RpcRequest {
  kind: 'request';
  id: number;
  method: string;
  params: unknown;
}
export interface RpcSuccessResponse {
  kind: 'response';
  id: number;
  ok: true;
  result: unknown;
}
export interface RpcErrorResponse {
  kind: 'response';
  id: number;
  ok: false;
  error: RpcError;
}
export interface RpcError {
  code:
    | 'permission_not_declared'
    | 'permission_not_granted'
    | 'method_not_found'
    | 'invalid_params'
    | 'not_found'
    | 'conflict'
    | 'unsupported_capability'
    | 'internal'
    | 'timeout';
  message: string;
  data?: unknown;
}
export interface RpcEvent {
  kind: 'event';
  topic: string;
  payload: unknown;
}

// rpc/ui.schema.json
export interface UiRpcSchemas {
  [k: string]: unknown;
}

// rpc/manifest.schema.json
export interface ManifestRpcSchemas {
  [k: string]: unknown;
}

// mcp-tools.schema.json
export interface McpToolSchemas {
  [k: string]: unknown;
}

// persistence.schema.json
export interface PersistenceSchemas {
  [k: string]: unknown;
}

