/* generated by scripts/codegen-ts.mjs; do not edit */
import Ajv, { type ErrorObject } from 'ajv';

export type SchemaName =
  | 'types.schema.json'
  | 'manifest.schema.json'
  | 'events.schema.json'
  | 'rpc/envelope.schema.json'
  | 'rpc/ui.schema.json'
  | 'rpc/manifest.schema.json'
  | 'mcp-tools.schema.json'
  | 'persistence.schema.json';

export type ValidationResult =
  | { ok: true }
  | { ok: false; errors: ErrorObject[] };

const schemas: Record<SchemaName, unknown> = {
  'types.schema.json': {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://polypore.dev/schemas/types.schema.json",
    "title": "PolyporeTypes",
    "definitions": {
      "AgentId": {
        "type": "string"
      },
      "Position": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "line",
          "column"
        ],
        "properties": {
          "line": {
            "type": "number"
          },
          "column": {
            "type": "number"
          }
        }
      },
      "Range": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "start",
          "end"
        ],
        "properties": {
          "start": {
            "$ref": "#/definitions/Position"
          },
          "end": {
            "$ref": "#/definitions/Position"
          }
        }
      },
      "TextEdit": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "range",
          "newText"
        ],
        "properties": {
          "range": {
            "$ref": "#/definitions/Range"
          },
          "newText": {
            "type": "string"
          }
        }
      },
      "Capability": {
        "type": "string",
        "enum": [
          "memory-dir",
          "slash-commands",
          "tool-servers",
          "compaction",
          "phase-reporting",
          "permission-flow",
          "subagent-spawn",
          "streaming",
          "tool-use"
        ]
      },
      "PanelCategory": {
        "type": "string",
        "enum": [
          "editor",
          "agent",
          "verify",
          "knowledge",
          "runtime",
          "other"
        ]
      },
      "HostPermission": {
        "type": "string",
        "enum": [
          "state.read",
          "editor.read",
          "editor.write",
          "editor.decorate",
          "knowledge.read",
          "knowledge.write",
          "tasks.read",
          "tasks.write",
          "diagnostics.read",
          "verify.read",
          "verify.run",
          "iterate.run",
          "chat.read",
          "chat.send",
          "chat.context",
          "agent.control",
          "history.read",
          "history.fork",
          "history.revert",
          "workspace.read",
          "workspace.write",
          "preview.read",
          "preview.register",
          "preview.refresh",
          "terminal.spawn",
          "terminal.stop",
          "terminal.write",
          "terminal.read",
          "fs.write",
          "ui.notify",
          "ui.confirm",
          "ui.openExternal",
          "ui.statusBar",
          "ui.input",
          "plugins.read",
          "plugins.write",
          "secrets.list",
          "secrets.use",
          "mcp.invoke",
          "skills.read",
          "skills.write",
          "skills.delete",
          "skills.invoke",
          "debug.read",
          "debug.control",
          "storage.read",
          "storage.write",
          "git.read",
          "git.write",
          "bus.publish",
          "http.fetch",
          "clipboard.read",
          "clipboard.write"
        ]
      },
      "AgentImpl": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "agent",
          "description",
          "available"
        ],
        "properties": {
          "agent": {
            "$ref": "#/definitions/AgentId"
          },
          "description": {
            "type": "string"
          },
          "available": {
            "type": "boolean"
          },
          "docsUrl": {
            "type": "string"
          }
        }
      },
      "AgentCapabilityMap": {
        "type": "object",
        "additionalProperties": {
          "anyOf": [
            {
              "$ref": "#/definitions/AgentImpl"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "PanelManualContent": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "summary",
          "tips"
        ],
        "properties": {
          "summary": {
            "type": "string"
          },
          "tips": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "externalDocsUrl": {
            "type": "string"
          }
        }
      },
      "PanelSettingSchema": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "fields"
        ],
        "properties": {
          "fields": {
            "type": "array"
          }
        }
      },
      "WorkspaceName": {
        "type": "string"
      },
      "Workspace": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "schemaVersion",
          "name",
          "dockview",
          "panelInstances"
        ],
        "properties": {
          "schemaVersion": {
            "const": 1
          },
          "name": {
            "$ref": "#/definitions/WorkspaceName"
          },
          "dockview": {
            "type": "object",
            "additionalProperties": true
          },
          "panelInstances": {
            "type": "object",
            "additionalProperties": true
          }
        }
      },
      "FileNode": {
        "oneOf": [
          {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "kind",
              "name",
              "path"
            ],
            "properties": {
              "kind": {
                "const": "file"
              },
              "name": {
                "type": "string"
              },
              "path": {
                "type": "string"
              },
              "subtitle": {
                "type": "string"
              }
            }
          },
          {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "kind",
              "name",
              "path",
              "children"
            ],
            "properties": {
              "kind": {
                "const": "folder"
              },
              "name": {
                "type": "string"
              },
              "path": {
                "type": "string"
              },
              "children": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/FileNode"
                }
              }
            }
          }
        ]
      },
      "DiagnosticSeverity": {
        "type": "string",
        "enum": [
          "error",
          "warn",
          "info",
          "hint"
        ]
      },
      "Diagnostic": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "severity",
          "source",
          "file",
          "range",
          "message"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "severity": {
            "$ref": "#/definitions/DiagnosticSeverity"
          },
          "source": {
            "type": "string"
          },
          "file": {
            "type": "string"
          },
          "range": {
            "$ref": "#/definitions/Range"
          },
          "message": {
            "type": "string"
          },
          "code": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "number"
              }
            ]
          }
        }
      },
      "DiagnosticFilter": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "severity": {
            "$ref": "#/definitions/DiagnosticSeverity"
          },
          "file": {
            "type": "string"
          },
          "source": {
            "type": "string"
          }
        }
      },
      "Task": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "label",
          "done",
          "createdAt",
          "createdBy"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "label": {
            "type": "string"
          },
          "done": {
            "type": "boolean"
          },
          "parentId": {
            "type": "string"
          },
          "panelHint": {
            "type": "string"
          },
          "createdAt": {
            "type": "number"
          },
          "createdBy": {
            "type": "string",
            "enum": [
              "user",
              "agent"
            ]
          }
        }
      },
      "VerifyStatus": {
        "type": "string",
        "enum": [
          "ok",
          "fail",
          "pending"
        ]
      },
      "VerifyRun": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "label",
          "command",
          "required",
          "status",
          "exitCode",
          "ranAt",
          "output",
          "durationMs"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "label": {
            "type": "string"
          },
          "command": {
            "type": "string"
          },
          "cwd": {
            "type": "string"
          },
          "required": {
            "type": "boolean"
          },
          "status": {
            "$ref": "#/definitions/VerifyStatus"
          },
          "exitCode": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ]
          },
          "ranAt": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ]
          },
          "output": {
            "type": "string"
          },
          "durationMs": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ]
          }
        }
      },
      "VerifyConfig": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "schemaVersion",
          "commands"
        ],
        "properties": {
          "schemaVersion": {
            "const": 1
          },
          "commands": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": true
            }
          }
        }
      },
      "HistoryEventKind": {
        "type": "string",
        "enum": [
          "tool-call",
          "file-write",
          "file-edit",
          "message",
          "phase-change",
          "snapshot"
        ]
      },
      "HistoryEvent": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "ts",
          "taskId",
          "source",
          "kind",
          "affectedFiles",
          "summary"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "ts": {
            "type": "number"
          },
          "taskId": {
            "type": "string"
          },
          "source": {
            "type": "string",
            "enum": [
              "agent",
              "human"
            ]
          },
          "kind": {
            "$ref": "#/definitions/HistoryEventKind"
          },
          "agentId": {
            "$ref": "#/definitions/AgentId"
          },
          "toolName": {
            "type": "string"
          },
          "phase": {
            "type": "string"
          },
          "affectedFiles": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "summary": {
            "type": "string"
          },
          "payload": {
            "type": "object",
            "additionalProperties": true
          },
          "snapshotId": {
            "type": "number"
          },
          "worktreeId": {
            "type": "string"
          },
          "snapshotCommit": {
            "type": "string"
          }
        }
      },
      "HistoryFilter": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "source": {
            "type": "string",
            "enum": [
              "agent",
              "human"
            ]
          },
          "kind": {
            "$ref": "#/definitions/HistoryEventKind"
          },
          "toolName": {
            "type": "string"
          },
          "file": {
            "type": "string"
          },
          "since": {
            "type": "number"
          },
          "until": {
            "type": "number"
          }
        }
      },
      "WorktreeRef": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "path",
          "branch",
          "forkedFromEventId"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "path": {
            "type": "string"
          },
          "branch": {
            "type": "string"
          },
          "forkedFromEventId": {
            "type": "string"
          }
        }
      },
      "KnowledgeNode": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "kind",
          "path"
        ],
        "properties": {
          "kind": {
            "type": "string",
            "enum": [
              "doc",
              "folder"
            ]
          },
          "path": {
            "type": "string"
          }
        }
      },
      "Handoff": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "summary",
          "nextSteps",
          "context"
        ],
        "properties": {
          "summary": {
            "type": "string"
          },
          "nextSteps": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "context": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "ChatMessage": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "sessionId",
          "by",
          "ts",
          "text"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "sessionId": {
            "type": "string"
          },
          "by": {
            "type": "string",
            "enum": [
              "user",
              "agent",
              "tool"
            ]
          },
          "ts": {
            "type": "number"
          },
          "text": {
            "type": "string"
          },
          "toolCallId": {
            "type": "string"
          }
        }
      },
      "ToolCall": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "sessionId",
          "agentId",
          "toolName",
          "summary",
          "status",
          "ts"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "sessionId": {
            "type": "string"
          },
          "agentId": {
            "$ref": "#/definitions/AgentId"
          },
          "toolName": {
            "type": "string"
          },
          "summary": {
            "type": "string"
          },
          "status": {
            "type": "string",
            "enum": [
              "ok",
              "live",
              "fail"
            ]
          },
          "ts": {
            "type": "number"
          },
          "historyEventId": {
            "type": "string"
          }
        }
      },
      "ChatSession": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "agent",
          "title",
          "createdAt"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "agent": {
            "$ref": "#/definitions/AgentId"
          },
          "title": {
            "type": "string"
          },
          "createdAt": {
            "type": "number"
          },
          "worktreeId": {
            "type": "string"
          }
        }
      },
      "WorkflowNodeStatus": {
        "type": "string",
        "enum": [
          "pending",
          "running",
          "done",
          "failed",
          "paused"
        ]
      },
      "WorkflowNode": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "id",
          "label",
          "level",
          "status"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "label": {
            "type": "string"
          },
          "level": {
            "type": "string",
            "enum": [
              "phase",
              "sub"
            ]
          },
          "status": {
            "$ref": "#/definitions/WorkflowNodeStatus"
          }
        }
      },
      "WorkflowEdge": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "source",
          "target"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "source": {
            "type": "string"
          },
          "target": {
            "type": "string"
          }
        }
      },
      "WorkflowGraph": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "schemaVersion",
          "taskId",
          "title",
          "enabled",
          "nodes",
          "edges"
        ],
        "properties": {
          "schemaVersion": {
            "const": 1
          },
          "taskId": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "enabled": {
            "type": "boolean"
          },
          "nodes": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/WorkflowNode"
            }
          },
          "edges": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/WorkflowEdge"
            }
          }
        }
      },
      "PreviewKind": {
        "type": "string",
        "enum": [
          "site",
          "desktop",
          "mobile",
          "cli",
          "game",
          "test"
        ]
      },
      "PreviewTarget": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "kind",
          "label",
          "command",
          "target",
          "registeredAt"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "kind": {
            "$ref": "#/definitions/PreviewKind"
          },
          "label": {
            "type": "string"
          },
          "command": {
            "type": "string"
          },
          "cwd": {
            "type": "string"
          },
          "target": {
            "type": "string"
          },
          "registeredAt": {
            "type": "number"
          },
          "agentId": {
            "$ref": "#/definitions/AgentId"
          }
        }
      },
      "TerminalRef": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "pid",
          "shell",
          "cwd"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "pid": {
            "type": "number"
          },
          "shell": {
            "type": "string"
          },
          "cwd": {
            "type": "string"
          }
        }
      },
      "FormationRole": {
        "type": "string"
      },
      "FormationNode": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "id",
          "role",
          "detail",
          "root",
          "status"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "role": {
            "$ref": "#/definitions/FormationRole"
          },
          "detail": {
            "type": "string"
          },
          "root": {
            "type": "boolean"
          },
          "status": {
            "type": "string",
            "enum": [
              "idle",
              "running",
              "waiting",
              "done",
              "failed"
            ]
          }
        }
      },
      "Formation": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "schemaVersion",
          "taskId",
          "nodes",
          "edges"
        ],
        "properties": {
          "schemaVersion": {
            "const": 1
          },
          "taskId": {
            "type": "string"
          },
          "nodes": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/FormationNode"
            }
          },
          "edges": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/WorkflowEdge"
            }
          }
        }
      },
      "SkillScope": {
        "type": "string",
        "enum": [
          "project",
          "user",
          "builtin"
        ]
      },
      "SkillRef": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "id",
          "name",
          "scope",
          "summary",
          "path",
          "updatedAt"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "scope": {
            "$ref": "#/definitions/SkillScope"
          },
          "summary": {
            "type": "string"
          },
          "path": {
            "type": "string"
          },
          "updatedAt": {
            "type": "number"
          }
        }
      },
      "Skill": {
        "allOf": [
          {
            "$ref": "#/definitions/SkillRef"
          },
          {
            "type": "object",
            "additionalProperties": true,
            "required": [
              "body",
              "createdAt"
            ],
            "properties": {
              "body": {
                "type": "string"
              },
              "createdAt": {
                "type": "number"
              }
            }
          }
        ]
      },
      "SecretScope": {
        "type": "string",
        "enum": [
          "user",
          "project"
        ]
      },
      "SecretRef": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "scope",
          "configured"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "scope": {
            "$ref": "#/definitions/SecretScope"
          },
          "service": {
            "type": "string"
          },
          "hint": {
            "type": "string"
          },
          "configured": {
            "type": "boolean"
          },
          "lastUsedAt": {
            "type": "number"
          }
        }
      },
      "SecretInvoke": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "id",
          "request"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "request": {
            "type": "object",
            "additionalProperties": true
          }
        }
      },
      "SecretInvokeResult": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "status",
          "headers",
          "body"
        ],
        "properties": {
          "status": {
            "type": "number"
          },
          "headers": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "body": {
            "type": "string"
          }
        }
      },
      "McpInvoke": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "server",
          "method",
          "args"
        ],
        "properties": {
          "server": {
            "type": "string"
          },
          "method": {
            "type": "string"
          },
          "args": {
            "type": "object",
            "additionalProperties": true
          },
          "authRef": {
            "type": "string"
          },
          "timeoutMs": {
            "type": "number"
          }
        }
      },
      "PluginRef": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "id",
          "version",
          "scope",
          "enabled",
          "installedAt"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "version": {
            "type": "string"
          },
          "scope": {
            "type": "string",
            "enum": [
              "project",
              "user",
              "builtin"
            ]
          },
          "enabled": {
            "type": "boolean"
          },
          "installedAt": {
            "type": "number"
          }
        }
      },
      "PluginStaging": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "stagingPath",
          "source",
          "fileTree",
          "candidates"
        ],
        "properties": {
          "stagingPath": {
            "type": "string"
          }
        }
      },
      "OpenPanelOpts": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "area": {
            "type": "string",
            "enum": [
              "center",
              "left",
              "right",
              "bottom"
            ]
          },
          "group": {
            "type": "string"
          },
          "active": {
            "type": "boolean"
          },
          "props": {
            "type": "object",
            "additionalProperties": true
          }
        }
      },
      "StateKey": {
        "type": "string",
        "enum": [
          "activeAgent",
          "agentConnected",
          "workspace",
          "activePanel",
          "agentPanels",
          "branch",
          "contextUsedPct",
          "context",
          "permissionMode",
          "loopCycle",
          "preview",
          "formation",
          "tasks",
          "diagnostics",
          "verifyRuns"
        ]
      }
    },
    "type": "object",
    "additionalProperties": true
  },
  'manifest.schema.json': {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://polypore.dev/schemas/manifest.schema.json",
    "title": "PanelManifest",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "schemaVersion",
      "id",
      "title",
      "icon",
      "version",
      "entry",
      "permissions",
      "capabilities",
      "category"
    ],
    "properties": {
      "schemaVersion": {
        "const": 1
      },
      "id": {
        "type": "string",
        "minLength": 1
      },
      "title": {
        "type": "string",
        "minLength": 1
      },
      "icon": {
        "type": "string",
        "minLength": 1,
        "maxLength": 4
      },
      "version": {
        "type": "string",
        "minLength": 1
      },
      "author": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          }
        }
      },
      "description": {
        "type": "string"
      },
      "entry": {
        "type": "string",
        "minLength": 1
      },
      "permissions": {
        "type": "array",
        "items": {
          "$ref": "types.schema.json#/definitions/HostPermission"
        }
      },
      "capabilities": {
        "type": "array",
        "items": {
          "$ref": "types.schema.json#/definitions/Capability"
        }
      },
      "category": {
        "$ref": "types.schema.json#/definitions/PanelCategory"
      },
      "defaultArea": {
        "type": "string",
        "enum": [
          "center",
          "left",
          "right",
          "bottom"
        ]
      },
      "settings": {
        "$ref": "types.schema.json#/definitions/PanelSettingSchema"
      },
      "manual": {
        "$ref": "types.schema.json#/definitions/PanelManualContent"
      }
    }
  },
  'events.schema.json': {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://polypore.dev/schemas/events.schema.json",
    "title": "AppEvent",
    "oneOf": [
      {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "event"
        ],
        "properties": {
          "type": {
            "const": "history:event"
          },
          "event": {
            "$ref": "types.schema.json#/definitions/HistoryEvent"
          }
        }
      },
      {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "nodes",
          "edges"
        ],
        "properties": {
          "type": {
            "const": "workflow:update"
          },
          "nodes": {
            "type": "array",
            "items": {
              "$ref": "types.schema.json#/definitions/WorkflowNode"
            }
          },
          "edges": {
            "type": "array",
            "items": {
              "$ref": "types.schema.json#/definitions/WorkflowEdge"
            }
          }
        }
      },
      {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "run"
        ],
        "properties": {
          "type": {
            "const": "verify:run-recorded"
          },
          "run": {
            "$ref": "types.schema.json#/definitions/VerifyRun"
          }
        }
      },
      {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "connected",
          "agent"
        ],
        "properties": {
          "type": {
            "const": "agent:connection-changed"
          },
          "connected": {
            "type": "boolean"
          },
          "agent": {
            "$ref": "types.schema.json#/definitions/AgentId"
          }
        }
      },
      {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "sessionId",
          "toolCall"
        ],
        "properties": {
          "type": {
            "const": "agent:tool-call"
          },
          "sessionId": {
            "type": "string"
          },
          "toolCall": {
            "$ref": "types.schema.json#/definitions/ToolCall"
          }
        }
      },
      {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "sessionId",
          "message"
        ],
        "properties": {
          "type": {
            "const": "chat:message"
          },
          "sessionId": {
            "type": "string"
          },
          "message": {
            "$ref": "types.schema.json#/definitions/ChatMessage"
          }
        }
      },
      {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "tasks"
        ],
        "properties": {
          "type": {
            "const": "tasks:changed"
          },
          "tasks": {
            "type": "array",
            "items": {
              "$ref": "types.schema.json#/definitions/Task"
            }
          }
        }
      },
      {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "path"
        ],
        "properties": {
          "type": {
            "const": "editor:opened"
          },
          "path": {
            "type": "string"
          }
        }
      },
      {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "path",
          "edits"
        ],
        "properties": {
          "type": {
            "const": "editor:edited"
          },
          "path": {
            "type": "string"
          },
          "edits": {
            "type": "array",
            "items": {
              "$ref": "types.schema.json#/definitions/TextEdit"
            }
          }
        }
      },
      {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "diagnostics"
        ],
        "properties": {
          "type": {
            "const": "diagnostics:changed"
          },
          "diagnostics": {
            "type": "array",
            "items": {
              "$ref": "types.schema.json#/definitions/Diagnostic"
            }
          }
        }
      },
      {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "path"
        ],
        "properties": {
          "type": {
            "const": "knowledge:changed"
          },
          "path": {
            "type": "string"
          }
        }
      },
      {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "instanceId",
          "panelId"
        ],
        "properties": {
          "type": {
            "const": "panel:opened"
          },
          "instanceId": {
            "type": "string"
          },
          "panelId": {
            "type": "string"
          },
          "area": {
            "type": "string",
            "enum": [
              "center",
              "left",
              "right",
              "bottom"
            ]
          }
        }
      },
      {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "instanceId"
        ],
        "properties": {
          "type": {
            "const": "panel:closed"
          },
          "instanceId": {
            "type": "string"
          }
        }
      },
      {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "target"
        ],
        "properties": {
          "type": {
            "const": "preview:registered"
          },
          "target": {
            "$ref": "types.schema.json#/definitions/PreviewTarget"
          }
        }
      },
      {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type"
        ],
        "properties": {
          "type": {
            "const": "preview:refresh-requested"
          }
        }
      },
      {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "formation"
        ],
        "properties": {
          "type": {
            "const": "formation:updated"
          },
          "formation": {
            "$ref": "types.schema.json#/definitions/Formation"
          }
        }
      },
      {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "key",
          "value"
        ],
        "properties": {
          "type": {
            "const": "state:changed"
          },
          "key": {
            "$ref": "types.schema.json#/definitions/StateKey"
          },
          "value": true
        }
      },
      {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "plugins"
        ],
        "properties": {
          "type": {
            "const": "plugins:changed"
          },
          "plugins": {
            "type": "array",
            "items": {
              "$ref": "types.schema.json#/definitions/PluginRef"
            }
          }
        }
      }
    ]
  },
  'rpc/envelope.schema.json': {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://polypore.dev/schemas/rpc/envelope.schema.json",
    "title": "RpcEnvelope",
    "oneOf": [
      {
        "title": "RpcRequest",
        "type": "object",
        "additionalProperties": false,
        "required": [
          "kind",
          "id",
          "method",
          "params"
        ],
        "properties": {
          "kind": {
            "const": "request"
          },
          "id": {
            "type": "number"
          },
          "method": {
            "type": "string"
          },
          "params": true
        }
      },
      {
        "title": "RpcSuccessResponse",
        "type": "object",
        "additionalProperties": false,
        "required": [
          "kind",
          "id",
          "ok",
          "result"
        ],
        "properties": {
          "kind": {
            "const": "response"
          },
          "id": {
            "type": "number"
          },
          "ok": {
            "const": true
          },
          "result": true
        }
      },
      {
        "title": "RpcErrorResponse",
        "type": "object",
        "additionalProperties": false,
        "required": [
          "kind",
          "id",
          "ok",
          "error"
        ],
        "properties": {
          "kind": {
            "const": "response"
          },
          "id": {
            "type": "number"
          },
          "ok": {
            "const": false
          },
          "error": {
            "$ref": "#/definitions/RpcError"
          }
        }
      },
      {
        "title": "RpcEvent",
        "type": "object",
        "additionalProperties": false,
        "required": [
          "kind",
          "topic",
          "payload"
        ],
        "properties": {
          "kind": {
            "const": "event"
          },
          "topic": {
            "type": "string"
          },
          "payload": true
        }
      }
    ],
    "definitions": {
      "RpcError": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "enum": [
              "permission_not_declared",
              "permission_not_granted",
              "method_not_found",
              "invalid_params",
              "not_found",
              "conflict",
              "unsupported_capability",
              "internal",
              "timeout"
            ]
          },
          "message": {
            "type": "string"
          },
          "data": true
        }
      }
    }
  },
  'rpc/ui.schema.json': {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://polypore.dev/schemas/rpc/ui.schema.json",
    "title": "UiRpcSchemas",
    "definitions": {
      "ui.notify.params": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "level",
          "msg"
        ],
        "properties": {
          "level": {
            "type": "string",
            "enum": [
              "info",
              "success",
              "warning",
              "warn",
              "error"
            ]
          },
          "msg": {
            "type": "string",
            "minLength": 1
          }
        }
      },
      "ui.notify.result": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "shown"
        ],
        "properties": {
          "shown": {
            "type": "boolean"
          }
        }
      },
      "ui.confirm.params": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "msg"
        ],
        "properties": {
          "msg": {
            "type": "string"
          }
        }
      },
      "ui.confirm.result": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "confirmed"
        ],
        "properties": {
          "confirmed": {
            "type": "boolean"
          }
        }
      },
      "ui.openExternal.params": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "url"
        ],
        "properties": {
          "url": {
            "type": "string",
            "pattern": "^https?://.+"
          }
        }
      },
      "ui.openExternal.result": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "opened"
        ],
        "properties": {
          "opened": {
            "type": "boolean"
          }
        }
      }
    },
    "type": "object",
    "additionalProperties": true
  },
  'rpc/manifest.schema.json': {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://polypore.dev/schemas/rpc/manifest.schema.json",
    "title": "ManifestRpcSchemas",
    "definitions": {
      "manifest.register.params": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "manifest"
        ],
        "properties": {
          "manifest": {
            "$ref": "../manifest.schema.json"
          }
        }
      },
      "manifest.register.result": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "registered",
          "panelId"
        ],
        "properties": {
          "registered": {
            "type": "boolean"
          },
          "panelId": {
            "type": "string"
          }
        }
      }
    },
    "type": "object",
    "additionalProperties": true
  },
  'mcp-tools.schema.json': {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://polypore.dev/schemas/mcp-tools.schema.json",
    "title": "McpToolSchemas",
    "definitions": {
      "empty.input": {
        "type": "object",
        "additionalProperties": false
      },
      "loose.object": {
        "type": "object",
        "additionalProperties": true
      },
      "string.id": {
        "type": "string",
        "minLength": 1
      },
      "skill.id": {
        "type": "string",
        "pattern": "^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
      },
      "string.array": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "polypore.manual.input": {
        "type": "object",
        "properties": {
          "section": {
            "type": "string"
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "polypore.state.get.input": {
        "type": "object",
        "properties": {
          "key": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "key"
        ],
        "additionalProperties": false
      },
      "polypore.editor.open.input": {
        "type": "object",
        "properties": {
          "path": {
            "type": "string",
            "minLength": 1
          },
          "line": {
            "type": "integer",
            "minimum": 1
          },
          "col": {
            "type": "integer",
            "minimum": 1
          }
        },
        "required": [
          "path"
        ],
        "additionalProperties": false
      },
      "polypore.editor.read.input": {
        "type": "object",
        "properties": {
          "path": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "path"
        ],
        "additionalProperties": false
      },
      "polypore.editor.search.input": {
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "minLength": 1
          },
          "regex": {
            "type": "boolean"
          },
          "glob": {
            "type": "string"
          },
          "limit": {
            "type": "integer",
            "minimum": 1,
            "maximum": 1000
          }
        },
        "required": [
          "query"
        ],
        "additionalProperties": false
      },
      "polypore.workspace.describe.input": {
        "type": "object",
        "properties": {},
        "required": [],
        "additionalProperties": false
      },
      "polypore.memory.list.input": {
        "type": "object",
        "properties": {
          "baseId": {
            "type": "string"
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "polypore.tasks.update.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "done": {
            "type": "boolean"
          },
          "label": {
            "type": "string",
            "minLength": 1
          },
          "parentId": {
            "type": "string"
          },
          "panelHint": {
            "type": "string"
          }
        },
        "required": [
          "id"
        ],
        "additionalProperties": false
      },
      "polypore.tasks.add.input": {
        "type": "object",
        "properties": {
          "label": {
            "type": "string",
            "minLength": 1
          },
          "panelHint": {
            "type": "string"
          }
        },
        "required": [
          "label"
        ],
        "additionalProperties": false
      },
      "polypore.tasks.list.input": {
        "type": "object",
        "properties": {},
        "required": [],
        "additionalProperties": false
      },
      "polypore.diagnostics.list.input": {
        "type": "object",
        "properties": {
          "severity": {
            "type": "string"
          },
          "file": {
            "type": "string"
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "polypore.verify.run.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "id"
        ],
        "additionalProperties": false
      },
      "polypore.verify.results.input": {
        "type": "object",
        "properties": {},
        "required": [],
        "additionalProperties": false
      },
      "polypore.verify.declare.input": {
        "type": "object",
        "properties": {
          "commands": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "minLength": 1
                },
                "label": {
                  "type": "string"
                },
                "command": {
                  "type": "string",
                  "minLength": 1
                },
                "required": {
                  "type": "boolean"
                }
              },
              "required": [
                "id",
                "command"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "commands"
        ],
        "additionalProperties": false
      },
      "polypore.format.run.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "file": {
            "type": "string"
          }
        },
        "required": [
          "id"
        ],
        "additionalProperties": false
      },
      "polypore.memory.read.input": {
        "type": "object",
        "properties": {
          "path": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "path"
        ],
        "additionalProperties": false
      },
      "polypore.memory.write.input": {
        "type": "object",
        "properties": {
          "path": {
            "type": "string",
            "minLength": 1
          },
          "content": {
            "type": "string"
          }
        },
        "required": [
          "path",
          "content"
        ],
        "additionalProperties": false
      },
      "polypore.memory.link.input": {
        "type": "object",
        "properties": {
          "from": {
            "type": "string",
            "minLength": 1
          },
          "to": {
            "type": "string",
            "minLength": 1
          },
          "displayText": {
            "type": "string"
          }
        },
        "required": [
          "from",
          "to"
        ],
        "additionalProperties": false
      },
      "polypore.memory.handoff.input": {
        "type": "object",
        "properties": {
          "summary": {
            "type": "string",
            "minLength": 1
          },
          "nextSteps": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "context": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "summary"
        ],
        "additionalProperties": false
      },
      "polypore.phase.report.input": {
        "type": "object",
        "properties": {
          "phase": {
            "type": "string",
            "minLength": 1
          },
          "status": {
            "type": "string",
            "enum": [
              "pending",
              "active",
              "blocked",
              "done"
            ]
          }
        },
        "required": [
          "phase",
          "status"
        ],
        "additionalProperties": false
      },
      "polypore.workflow.update.input": {
        "type": "object",
        "properties": {
          "nodes": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": true
            }
          },
          "edges": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": true
            }
          }
        },
        "required": [
          "nodes",
          "edges"
        ],
        "additionalProperties": false
      },
      "polypore.panel.open.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "area": {
            "type": "string",
            "enum": [
              "center",
              "left",
              "right",
              "bottom"
            ]
          }
        },
        "required": [
          "id"
        ],
        "additionalProperties": false
      },
      "polypore.panel.close.input": {
        "type": "object",
        "properties": {
          "instanceId": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "instanceId"
        ],
        "additionalProperties": false
      },
      "polypore.ui.notify.input": {
        "type": "object",
        "properties": {
          "level": {
            "type": "string",
            "enum": [
              "info",
              "success",
              "warning",
              "error"
            ]
          },
          "msg": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "level",
          "msg"
        ],
        "additionalProperties": false
      },
      "polypore.preview.register.input": {
        "type": "object",
        "properties": {
          "kind": {
            "type": "string",
            "enum": [
              "site",
              "desktop",
              "mobile",
              "cli",
              "game",
              "test"
            ]
          },
          "command": {
            "type": "string",
            "minLength": 1
          },
          "target": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "kind",
          "command",
          "target"
        ],
        "additionalProperties": false
      },
      "polypore.preview.refresh.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "polypore.history.events.input": {
        "type": "object",
        "properties": {
          "limit": {
            "type": "integer",
            "minimum": 1
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "polypore.history.fork.input": {
        "type": "object",
        "properties": {
          "eventId": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "eventId"
        ],
        "additionalProperties": false
      },
      "polypore.adr.record.input": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "minLength": 1
          },
          "body": {
            "type": "string"
          }
        },
        "required": [
          "title",
          "body"
        ],
        "additionalProperties": false
      },
      "polypore.mcp.invoke.input": {
        "type": "object",
        "properties": {
          "server": {
            "type": "string",
            "minLength": 1
          },
          "method": {
            "type": "string",
            "minLength": 1
          },
          "args": {
            "type": "object",
            "additionalProperties": true
          },
          "authRef": {
            "type": "string"
          }
        },
        "required": [
          "server",
          "method"
        ],
        "additionalProperties": false
      },
      "polypore.plugins.fetch.input": {
        "type": "object",
        "properties": {
          "url": {
            "type": "string",
            "minLength": 1
          },
          "ref": {
            "type": "string"
          }
        },
        "required": [
          "url"
        ],
        "additionalProperties": false
      },
      "polypore.plugins.scan.input": {
        "type": "object",
        "properties": {
          "stagingPath": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "stagingPath"
        ],
        "additionalProperties": false
      },
      "polypore.plugins.inspect.input": {
        "type": "object",
        "properties": {
          "stagingPath": {
            "type": "string",
            "minLength": 1
          },
          "manifestPath": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "stagingPath",
          "manifestPath"
        ],
        "additionalProperties": false
      },
      "polypore.plugins.install.input": {
        "type": "object",
        "properties": {
          "stagingPath": {
            "type": "string",
            "minLength": 1
          },
          "manifestPath": {
            "type": "string",
            "minLength": 1
          },
          "scope": {
            "type": "string",
            "enum": [
              "project",
              "user"
            ]
          }
        },
        "required": [
          "stagingPath",
          "manifestPath"
        ],
        "additionalProperties": false
      },
      "polypore.plugins.list.input": {
        "type": "object",
        "properties": {
          "scope": {
            "type": "string",
            "enum": [
              "project",
              "user",
              "builtin"
            ]
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "polypore.plugins.enable.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "id"
        ],
        "additionalProperties": false
      },
      "polypore.plugins.disable.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "id"
        ],
        "additionalProperties": false
      },
      "polypore.plugins.uninstall.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "id"
        ],
        "additionalProperties": false
      },
      "polypore.secrets.list.input": {
        "type": "object",
        "properties": {
          "scope": {
            "type": "string",
            "enum": [
              "project",
              "user"
            ]
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "polypore.secrets.has.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "scope": {
            "type": "string",
            "enum": [
              "project",
              "user"
            ]
          }
        },
        "required": [
          "id"
        ],
        "additionalProperties": false
      },
      "polypore.secrets.use.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "scope": {
            "type": "string",
            "enum": [
              "project",
              "user"
            ]
          },
          "request": {
            "type": "object",
            "properties": {
              "url": {
                "type": "string",
                "minLength": 1
              },
              "method": {
                "type": "string"
              },
              "headers": {
                "type": "object",
                "additionalProperties": {
                  "type": "string"
                }
              },
              "body": {},
              "timeoutMs": {
                "type": "integer",
                "minimum": 1,
                "maximum": 120000
              },
              "allowInsecure": {
                "type": "boolean"
              }
            },
            "required": [
              "url"
            ],
            "additionalProperties": false
          }
        },
        "required": [
          "id",
          "request"
        ],
        "additionalProperties": false
      },
      "polypore.skills.list.input": {
        "type": "object",
        "properties": {
          "scope": {
            "type": "string",
            "enum": [
              "project",
              "user"
            ]
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "polypore.skills.read.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "id"
        ],
        "additionalProperties": false
      },
      "polypore.skills.invoke.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "sessionId": {
            "type": "string"
          },
          "args": {
            "type": "object",
            "additionalProperties": true
          }
        },
        "required": [
          "id"
        ],
        "additionalProperties": false
      },
      "polypore.skills.create.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "name": {
            "type": "string",
            "minLength": 1
          },
          "body": {
            "type": "string"
          }
        },
        "required": [
          "body"
        ],
        "additionalProperties": false,
        "anyOf": [
          {
            "required": [
              "id"
            ]
          },
          {
            "required": [
              "name"
            ]
          }
        ]
      },
      "polypore.skills.update.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "body": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "body"
        ],
        "additionalProperties": false
      },
      "polypore.skills.delete.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "id"
        ],
        "additionalProperties": false
      },
      "polypore.skillsets.list.input": {
        "type": "object",
        "properties": {},
        "required": [],
        "additionalProperties": false
      },
      "polypore.skillsets.read.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "id"
        ],
        "additionalProperties": false
      },
      "polypore.skillsets.upsert.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "title": {
            "type": "string",
            "minLength": 1
          },
          "summary": {
            "type": "string"
          },
          "version": {
            "type": "string"
          }
        },
        "required": [
          "title"
        ],
        "additionalProperties": false
      },
      "polypore.skillsets.delete.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "id"
        ],
        "additionalProperties": false
      },
      "polypore.skills.publish.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "agents": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "claude",
                "codex"
              ]
            }
          }
        },
        "required": [
          "id",
          "agents"
        ],
        "additionalProperties": false
      },
      "polypore.mcp.servers.list.input": {
        "type": "object",
        "properties": {
          "scope": {
            "type": "string",
            "enum": [
              "project",
              "user",
              "polypore"
            ]
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "polypore.mcp.servers.upsert.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string",
            "minLength": 1
          },
          "url": {
            "type": "string",
            "minLength": 1
          },
          "scope": {
            "type": "string",
            "enum": [
              "project",
              "user",
              "polypore"
            ]
          },
          "headers": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "authRef": {
            "type": "string"
          },
          "allowInsecure": {
            "type": "boolean"
          },
          "timeoutMs": {
            "type": "integer",
            "minimum": 1,
            "maximum": 120000
          }
        },
        "required": [
          "name",
          "url"
        ],
        "additionalProperties": false
      },
      "polypore.mcp.servers.delete.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "id"
        ],
        "additionalProperties": false
      },
      "polypore.mcp.servers.test.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "id"
        ],
        "additionalProperties": false
      },
      "polypore.formation.upsert.input": {
        "type": "object",
        "properties": {
          "nodes": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": true
            }
          },
          "edges": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": true
            }
          }
        },
        "required": [
          "nodes",
          "edges"
        ],
        "additionalProperties": false
      },
      "polypore.debug.probe.input": {
        "type": "object",
        "properties": {
          "adapter": {
            "type": "string"
          },
          "config": {
            "type": "object",
            "additionalProperties": true
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "polypore.debug.start.input": {
        "type": "object",
        "properties": {
          "scenario": {
            "type": "object",
            "properties": {
              "title": {
                "type": "string",
                "minLength": 1
              },
              "whatsWrong": {
                "type": "string"
              }
            },
            "required": [
              "title"
            ],
            "additionalProperties": false
          },
          "adapter": {
            "type": "string"
          },
          "config": {
            "type": "object",
            "additionalProperties": true
          },
          "trust": {
            "type": "string",
            "enum": [
              "observe",
              "evaluate",
              "off"
            ]
          }
        },
        "required": [
          "scenario"
        ],
        "additionalProperties": false
      },
      "polypore.debug.setBreakpoints.input": {
        "type": "object",
        "properties": {
          "file": {
            "type": "string",
            "minLength": 1
          },
          "breakpoints": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "line": {
                  "type": "integer",
                  "minimum": 1
                },
                "condition": {
                  "type": "string"
                },
                "hitCondition": {
                  "type": "string"
                },
                "logMessage": {
                  "type": "string"
                }
              },
              "required": [
                "line"
              ],
              "additionalProperties": false
            }
          },
          "setBy": {
            "type": "string",
            "enum": [
              "agent",
              "human"
            ]
          }
        },
        "required": [
          "file",
          "breakpoints"
        ],
        "additionalProperties": false
      },
      "polypore.debug.addBreakpoint.input": {
        "type": "object",
        "properties": {
          "file": {
            "type": "string",
            "minLength": 1
          },
          "line": {
            "type": "integer",
            "minimum": 1
          },
          "condition": {
            "type": "string"
          }
        },
        "required": [
          "file",
          "line"
        ],
        "additionalProperties": false
      },
      "polypore.debug.removeBreakpoint.input": {
        "type": "object",
        "properties": {
          "file": {
            "type": "string",
            "minLength": 1
          },
          "line": {
            "type": "integer",
            "minimum": 1
          }
        },
        "required": [
          "file",
          "line"
        ],
        "additionalProperties": false
      },
      "polypore.debug.continue.input": {
        "type": "object",
        "properties": {
          "threadId": {
            "type": "integer"
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "polypore.debug.stepOver.input": {
        "type": "object",
        "properties": {
          "threadId": {
            "type": "integer"
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "polypore.debug.stepIn.input": {
        "type": "object",
        "properties": {
          "threadId": {
            "type": "integer"
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "polypore.debug.stepOut.input": {
        "type": "object",
        "properties": {
          "threadId": {
            "type": "integer"
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "polypore.debug.pause.input": {
        "type": "object",
        "properties": {
          "threadId": {
            "type": "integer"
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "polypore.debug.stackTrace.input": {
        "type": "object",
        "properties": {
          "threadId": {
            "type": "integer"
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "polypore.debug.scopes.input": {
        "type": "object",
        "properties": {
          "frameId": {
            "type": "integer"
          }
        },
        "required": [
          "frameId"
        ],
        "additionalProperties": false
      },
      "polypore.debug.variables.input": {
        "type": "object",
        "properties": {
          "variablesReference": {
            "type": "integer"
          }
        },
        "required": [
          "variablesReference"
        ],
        "additionalProperties": false
      },
      "polypore.debug.evaluate.input": {
        "type": "object",
        "properties": {
          "expression": {
            "type": "string",
            "minLength": 1
          },
          "frameId": {
            "type": "integer"
          }
        },
        "required": [
          "expression"
        ],
        "additionalProperties": false
      },
      "polypore.debug.capture.screenshot.input": {
        "type": "object",
        "properties": {
          "target": {
            "type": "string"
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "polypore.debug.capture.console.input": {
        "type": "object",
        "properties": {
          "limit": {
            "type": "integer",
            "minimum": 1
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "polypore.debug.capture.dom.input": {
        "type": "object",
        "properties": {
          "selector": {
            "type": "string"
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "polypore.debug.capture.network.input": {
        "type": "object",
        "properties": {},
        "required": [],
        "additionalProperties": false
      },
      "polypore.debug.roadblock.input": {
        "type": "object",
        "properties": {
          "ask": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "ask"
        ],
        "additionalProperties": false
      },
      "polypore.debug.roadblock.resolve.input": {
        "type": "object",
        "properties": {},
        "required": [],
        "additionalProperties": false
      },
      "polypore.debug.rootCause.input": {
        "type": "object",
        "properties": {
          "summary": {
            "type": "string",
            "minLength": 1
          },
          "file": {
            "type": "string"
          },
          "line": {
            "type": "integer"
          }
        },
        "required": [
          "summary"
        ],
        "additionalProperties": false
      },
      "polypore.debug.sessions.input": {
        "type": "object",
        "properties": {},
        "required": [],
        "additionalProperties": false
      },
      "polypore.debug.select.input": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "id"
        ],
        "additionalProperties": false
      },
      "polypore.debug.state.input": {
        "type": "object",
        "properties": {},
        "required": [],
        "additionalProperties": false
      },
      "polypore.debug.stop.input": {
        "type": "object",
        "properties": {},
        "required": [],
        "additionalProperties": false
      },
      "polypore.debug.capabilities.input": {
        "type": "object",
        "properties": {},
        "required": [],
        "additionalProperties": false
      },
      "polypore.debug.navigate.input": {
        "type": "object",
        "properties": {
          "url": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "url"
        ],
        "additionalProperties": false
      },
      "polypore.debug.click.input": {
        "type": "object",
        "properties": {
          "selector": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "selector"
        ],
        "additionalProperties": false
      },
      "polypore.debug.fill.input": {
        "type": "object",
        "properties": {
          "selector": {
            "type": "string",
            "minLength": 1
          },
          "text": {
            "type": "string"
          }
        },
        "required": [
          "selector",
          "text"
        ],
        "additionalProperties": false
      },
      "polypore.debug.login.input": {
        "type": "object",
        "properties": {
          "url": {
            "type": "string"
          },
          "usernameSelector": {
            "type": "string",
            "minLength": 1
          },
          "passwordSelector": {
            "type": "string",
            "minLength": 1
          },
          "usernameSecret": {
            "type": "string",
            "minLength": 1
          },
          "passwordSecret": {
            "type": "string",
            "minLength": 1
          },
          "submitSelector": {
            "type": "string"
          },
          "scope": {
            "type": "string",
            "enum": [
              "project",
              "user"
            ]
          }
        },
        "required": [
          "usernameSelector",
          "passwordSelector",
          "usernameSecret",
          "passwordSecret"
        ],
        "additionalProperties": false
      }
    },
    "type": "object",
    "additionalProperties": true
  },
  'persistence.schema.json': {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://polypore.dev/schemas/persistence.schema.json",
    "title": "PersistenceSchemas",
    "definitions": {
      "WorkspaceFile": {
        "$ref": "types.schema.json#/definitions/Workspace"
      },
      "VerifyConfigFile": {
        "$ref": "types.schema.json#/definitions/VerifyConfig"
      },
      "FormationFile": {
        "$ref": "types.schema.json#/definitions/Formation"
      },
      "TaskFile": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "schemaVersion",
          "tasks"
        ],
        "properties": {
          "schemaVersion": {
            "const": 1
          },
          "tasks": {
            "type": "array",
            "items": {
              "$ref": "types.schema.json#/definitions/Task"
            }
          }
        }
      }
    },
    "type": "object",
    "additionalProperties": true
  }
};

const ajv = new Ajv({ allErrors: true, strict: false, schemas: Object.values(schemas) as object[] });
const validators = new Map<string, ReturnType<typeof ajv.compile>>();

export function schemaFor(name: SchemaName) {
  return schemas[name];
}

export function validateSchema(name: SchemaName, data: unknown): ValidationResult {
  let validate = validators.get(name);
  if (!validate) {
    validate = ajv.compile(schemas[name] as object);
    validators.set(name, validate);
  }
  const ok = validate(data);
  return ok ? { ok: true } : { ok: false, errors: [...(validate.errors ?? [])] };
}

export function validateRef(ref: string, data: unknown): ValidationResult {
  const validate = ajv.getSchema(ref);
  if (!validate) {
    return { ok: false, errors: [{ instancePath: '', schemaPath: ref, keyword: 'schema', params: {}, message: 'schema not found' }] as ErrorObject[] };
  }
  const ok = validate(data);
  return ok ? { ok: true } : { ok: false, errors: [...(validate.errors ?? [])] };
}
