import { compile } from 'json-schema-to-typescript';
import fs from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();
const schemasDir = path.join(root, 'schemas');
const sdkDir = path.join(root, 'packages/sdk/src');

const schemaFiles = [
  'types.schema.json',
  'manifest.schema.json',
  'events.schema.json',
  'rpc/envelope.schema.json',
  'rpc/ui.schema.json',
  'rpc/manifest.schema.json',
  'mcp-tools.schema.json',
  'persistence.schema.json',
];

async function readSchema(relPath) {
  const fullPath = path.join(schemasDir, relPath);
  return JSON.parse(await fs.readFile(fullPath, 'utf8'));
}

function rewriteRefs(value, relPath) {
  if (Array.isArray(value)) return value.map((item) => rewriteRefs(item, relPath));
  if (!value || typeof value !== 'object') return value;
  const next = {};
  for (const [key, item] of Object.entries(value)) {
    if (key === '$ref' && typeof item === 'string' && !item.startsWith('#') && !item.startsWith('http')) {
      const [refPath, pointer = ''] = item.split('#');
      const absRef = path.resolve(schemasDir, path.dirname(relPath), refPath);
      next[key] = `${absRef}${pointer ? `#${pointer}` : ''}`;
    } else {
      next[key] = rewriteRefs(item, relPath);
    }
  }
  return next;
}

await fs.mkdir(sdkDir, { recursive: true });

let typesOut = [
  '/* generated by scripts/codegen-ts.mjs; do not edit */',
  '',
];

for (const relPath of schemaFiles) {
  const schema = rewriteRefs(await readSchema(relPath), relPath);
  const ts = await compile(schema, schema.title ?? path.basename(relPath), {
    bannerComment: '',
    cwd: schemasDir,
    declareExternallyReferenced: true,
    enableConstEnums: false,
    style: { singleQuote: true, semi: true },
  });
  typesOut.push(`// ${relPath}`, ts.trim(), '');
}

await fs.writeFile(path.join(sdkDir, 'types.gen.ts'), `${typesOut.join('\n')}\n`);

const schemaEntries = [];
for (const relPath of schemaFiles) {
  const schema = await readSchema(relPath);
  schemaEntries.push({ relPath, schema });
}

const validatorsOut = `/* generated by scripts/codegen-ts.mjs; do not edit */
import Ajv, { type ErrorObject } from 'ajv';

export type SchemaName =
${schemaEntries.map(({ relPath }) => `  | '${relPath}'`).join('\n')};

export type ValidationResult =
  | { ok: true }
  | { ok: false; errors: ErrorObject[] };

const schemas: Record<SchemaName, unknown> = {
${schemaEntries.map(({ relPath, schema }) => `  '${relPath}': ${JSON.stringify(schema, null, 2).replace(/\n/g, '\n  ')}`).join(',\n')}
};

const ajv = new Ajv({ allErrors: true, strict: false, schemas: Object.values(schemas) as object[] });
const validators = new Map<string, ReturnType<typeof ajv.compile>>();

export function schemaFor(name: SchemaName) {
  return schemas[name];
}

export function validateSchema(name: SchemaName, data: unknown): ValidationResult {
  let validate = validators.get(name);
  if (!validate) {
    validate = ajv.compile(schemas[name] as object);
    validators.set(name, validate);
  }
  const ok = validate(data);
  return ok ? { ok: true } : { ok: false, errors: [...(validate.errors ?? [])] };
}

export function validateRef(ref: string, data: unknown): ValidationResult {
  const validate = ajv.getSchema(ref);
  if (!validate) {
    return { ok: false, errors: [{ instancePath: '', schemaPath: ref, keyword: 'schema', params: {}, message: 'schema not found' }] as ErrorObject[] };
  }
  const ok = validate(data);
  return ok ? { ok: true } : { ok: false, errors: [...(validate.errors ?? [])] };
}
`;

await fs.writeFile(path.join(sdkDir, 'validators.gen.ts'), validatorsOut);

/* the Rust shell validates envelopes against the same schemas/ directory
   via serde_json + ad-hoc checks; there's no typify yet, so we don't emit
   a Rust types_gen.rs placeholder. when typify lands this is where the
   real codegen lives. */

console.log(`generated ${schemaFiles.length} schema bindings`);
